Console.WriteLine("Hello! Please, tell me your name: ");
string name = Console.ReadLine();
Console.WriteLine("Hello! Please, tell me your age: ");
string? age = Console.ReadLine();
int.TryParse(age, out int ageVerified);
Console.WriteLine("Hello! Please, tell me your favourite number: ");
string? favNum = Console.ReadLine();
int.TryParse(favNum, out int favNumVerified);
int thisYear = 2025;
int ClientsYearOfBirth = thisYear - ageVerified;
Console.WriteLine($"Thanks! So, your name is {name}, you are {ageVerified} years old and your favourite number is {favNumVerified}! I bet your birth year is {ClientsYearOfBirth}");
